### ISSUE TITLE
Paper 1.20.2 issue

### ISSUE THREAD

**Issue by M3II0** [Fierioziy/ParticleNativeAPI#11]
Caused by: sk.m3ii0.magicalwands.code.particles.api.utils.ParticleException: Could not find name for void method(Packet) in net.minecraft.server.network.PlayerConnection class.at sk.m3ii0.magicalwands.code.particles.core.asm.utils.RefUtils.tryInferMethodName(RefUtils.java:126) ~[MagicalWands.jar:?]at sk.m3ii0.magicalwands.code.particles.core.asm.utils.InternalResolver.getSendPacketMethodName_1_18(InternalResolver.java:259) ~[MagicalWands.jar:?]at sk.m3ii0.magicalwands.code.particles.core.asm.packet.ParticlePacketProvider_1_17.<init>(ParticlePacketProvider_1_17.java:16) ~[MagicalWands.jar:?]at sk.m3ii0.magicalwands.code.particles.core.asm.ContextASM.<init>(ContextASM.java:78) ~[MagicalWands.jar:?]at sk.m3ii0.magicalwands.code.particles.core.ParticleNativeCore.setupCore(ParticleNativeCore.java:55) ~[MagicalWands.jar:?]... 11 more

1.20.2 - Paper
build 217, to be more precise

(Works fine on my purpur server, one customer got this error)

**Comment by Fierioziy** [comment]
It looks like they used an older version of your plugin (with my api in version 4.0.0), because `InternalResolver.getSendPacketMethodName_1_18()` is now also used to confirm it's on version 1.19.3 - 1.19.4, so this stacktrace should not occur on 1.20.2 (even if Paper has something different, but I don't think so)

**Comment by M3II0** [comment]
It works for me so Im confused too. Purpur is Paper framework and Paper is Spigot framework so.

**Comment by M3II0** [comment]
I'll let you know

**Comment by M3II0** [comment]
Alright don't mind. Spigot didn't save my resource update. I announced update on my discord and spigot forgot I guess. It's updated now and works. Thanks

**Comment by Fierioziy** [comment]
Ok, good to hear
